export default booksPaths = {
  Genesis: require("./Genesis.json"),
  //   Exodus: require("./Exodus.json"),
  //   Leviticus: require("./Leviticus.json"),
  //   Numbers: require("./Numbers.json"),
  //   Deuteronomy: require("./Deuteronomy.json"),
  //   Joshua: require("./Joshua.json"),
  //   Judges: require("./Judges.json"),
  //   Ruth: require("./Ruth.json"),
  //   "I Samuel": require("./I Samuel.json"),
  //   "II Samuel": require("./II Samuel.json"),
  //   "I Kings": require("./I Kings.json"),
  //   "II Kings": require("./II Kings.json"),
  //   "I Chronicles": require("./I Chronicles.json"),
  //   "II Chronicles": require("./II Chronicles.json"),
  //   Ezra: require("./Ezra.json"),
  //   Nehemiah: require("./Nehemiah.json"),
  //   Esther: require("./Esther.json"),
  //   Job: require("./Job.json"),
  //   Psalms: require("./Psalms.json"),
  //   Proverbs: require("./Proverbs.json"),
  //   Ecclesiastes: require("./Ecclesiastes.json"),
  //   "Song of Solomon": require("./Song of Solomon.json"),
  //   Isaiah: require("./Isaiah.json"),
  //   Jeremiah: require("./Jeremiah.json"),
  //   Lamentations: require("./Lamentations.json"),
  //   Ezekiel: require("./Ezekiel.json"),
  //   Daniel: require("./Daniel.json"),
  //   Hosea: require("./Hosea.json"),
  //   Joel: require("./Joel.json"),
  //   Amos: require("./Amos.json"),
  //   Obadiah: require("./Obadiah.json"),
  //   Jonah: require("./Jonah.json"),
  //   Micah: require("./Micah.json"),
  //   Nahum: require("./Nahum.json"),
  //   Habakkuk: require("./Habakkuk.json"),
  //   Zephaniah: require("./Zephaniah.json"),
  //   Haggai: require("./Haggai.json"),
  //   Zechariah: require("./Zechariah.json"),
  //   Malachi: require("./Malachi.json"),
  //   Matthew: require("./Matthew.json"),
  //   Mark: require("./Mark.json"),
  //   Luke: require("./Luke.json"),
  //   John: require("./John.json"),
  //   Acts: require("./Acts.json"),
  //   Romans: require("./Romans.json"),
  //   "I Corinthians": require("./I Corinthians.json"),
  //   "II Corinthians": require("./II Corinthians.json"),
  //   Galatians: require("./Galatians.json"),
  //   Ephesians: require("./Ephesians.json"),
  //   Philippians: require("./Philippians.json"),
  //   Colossians: require("./Colossians.json"),
  //   "I Thessalonians": require("./I Thessalonians.json"),
  //   "II Thessalonians": require("./II Thessalonians.json"),
  //   "I Timothy": require("./I Timothy.json"),
  //   "II Timothy": require("./II Timothy.json"),
  //   Titus: require("./Titus.json"),
  //   Philemon: require("./Philemon.json"),
  //   Hebrews: require("./Hebrews.json"),
  //   James: require("./James.json"),
  //   "I Peter": require("./I Peter.json"),
  //   "II Peter": require("./II Peter.json"),
  "I John": require("./I John.json"),
  //   "II John": require("./II John.json"),
  //   "III John": require("./III John.json"),
  //   Jude: require("./Jude.json"),
  //   Revelation: require("./Revelation.json"),
};
